Nichobros : Bichoto.o BolFuego.o BolFuSal.o CaeCucho.o Caparatuzo.o Cartel.o Colec.o Explo.o Juanchi.o Mapa.o Moneda.o Nichobros.o Nicholas.o PinPalo.o PlatCae.o PlatLat.o PuenCae.o Puerta.o Rayo.o Reboter.o Robots.o Sauriolo.o Secuen.o Teleport.o Tortuga.o Triturin.o VarJuego.o VerdeLoc.o RutinasSDL/rutinasSDL.o
		g++ Bichoto.o BolFuego.o BolFuSal.o CaeCucho.o Caparatuzo.o Cartel.o Colec.o Explo.o Juanchi.o Mapa.o Moneda.o Nichobros.o Nicholas.o PinPalo.o PlatCae.o PlatLat.o PuenCae.o Puerta.o Rayo.o Reboter.o Robots.o Sauriolo.o Secuen.o Teleport.o Tortuga.o Triturin.o VarJuego.o VerdeLoc.o RutinasSDL/rutinasSDL.o -o Nichobros -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer

Bichoto.o : Bichoto.cpp RutinasSDL/rutinasSDL.h Bichoto.h InfoObj.h Colec.h Cartel.h DDInc.h VarJuego.h Mapa.h Nicholas.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h Tortuga.h
		g++ -c -Wall -o Bichoto.o Bichoto.cpp

BolFuego.o : BolFuego.cpp RutinasSDL/rutinasSDL.h BolFuego.h Colec.h InfoObj.h DDInc.h VarJuego.h Mapa.h
		g++ -c -Wall -o BolFuego.o BolFuego.cpp

BolFuSal.o : BolFuSal.cpp RutinasSDL/rutinasSDL.h BolFuSal.h Colec.h InfoObj.h DDInc.h VarJuego.h Mapa.h
		g++ -c -Wall -o BolFuSal.o BolFuSal.cpp

CaeCucho.o : CaeCucho.cpp RutinasSDL/rutinasSDL.h Secuen.h InfoObj.h Colec.h VarJuego.h Mapa.h DDInc.h CaeCucho.h Nicholas.h Cartel.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h
		g++ -c -Wall -o CaeCucho.o CaeCucho.cpp

Caparatuzo.o : Caparatuzo.cpp RutinasSDL/rutinasSDL.h Caparatuzo.h InfoObj.h Colec.h Cartel.h DDInc.h VarJuego.h Mapa.h Nicholas.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h Tortuga.h
		g++ -c -Wall -o Caparatuzo.o Caparatuzo.cpp

Cartel.o : Cartel.cpp RutinasSDL/rutinasSDL.h Cartel.h DDInc.h InfoObj.h Colec.h VarJuego.h Mapa.h
		g++ -c -Wall -o Cartel.o Cartel.cpp

Colec.o : Colec.cpp Colec.h
		g++ -c -Wall -o Colec.o Colec.cpp

Explo.o : Explo.cpp RutinasSDL/rutinasSDL.h Explo.h InfoObj.h Colec.h VarJuego.h Mapa.h DDInc.h
		g++ -c -Wall -o Explo.o Explo.cpp

Juanchi.o : Juanchi.cpp RutinasSDL/rutinasSDL.h Juanchi.h InfoObj.h Colec.h Cartel.h DDInc.h VarJuego.h Mapa.h Nicholas.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h Tortuga.h
		g++ -c -Wall -o Juanchi.o Juanchi.cpp

Mapa.o : Mapa.cpp Mapa.h InfoObj.h
		g++ -c -Wall -o Mapa.o Mapa.cpp

Moneda.o : Moneda.cpp RutinasSDL/rutinasSDL.h Moneda.h DDInc.h InfoObj.h Colec.h VarJuego.h Mapa.h Cartel.h
		g++ -c -Wall -o Moneda.o Moneda.cpp

Nichobros.o : Nichobros.cpp RutinasSDL/rutinasSDL.h Nichobros.h Cartel.h DDInc.h InfoObj.h Colec.h VarJuego.h Mapa.h Debug.h Explo.h Juanchi.h Nicholas.h Moneda.h BolFuego.h PuenCae.h Triturin.h Rayo.h Tortuga.h Reboter.h BolFuSal.h VerdeLoc.h Robots.h PlatCae.h PinPalo.h PlatLat.h CaeCucho.h Teleport.h Puerta.h Sauriolo.h Caparatuzo.h Bichoto.h
		g++ -c -Wall -o Nichobros.o Nichobros.cpp

Nicholas.o : Nicholas.cpp RutinasSDL/rutinasSDL.h Teleport.h DDInc.h InfoObj.h VarJuego.h Mapa.h Colec.h Nicholas.h Cartel.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h
		g++ -c -Wall -o Nicholas.o Nicholas.cpp

PinPalo.o : PinPalo.cpp RutinasSDL/rutinasSDL.h PinPalo.h Colec.h InfoObj.h DDInc.h VarJuego.h Mapa.h
		g++ -c -Wall -o PinPalo.o PinPalo.cpp

PlatCae.o : PlatCae.cpp RutinasSDL/rutinasSDL.h PlatCae.h Nicholas.h InfoObj.h VarJuego.h Mapa.h DDInc.h Colec.h Cartel.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h
		g++ -c -Wall -o PlatCae.o PlatCae.cpp

PlatLat.o : PlatLat.cpp RutinasSDL/rutinasSDL.h PlatLat.h Nicholas.h InfoObj.h VarJuego.h Mapa.h DDInc.h Colec.h Cartel.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h
		g++ -c -Wall -o PlatLat.o PlatLat.cpp

PuenCae.o : PuenCae.cpp RutinasSDL/rutinasSDL.h PuenCae.h Colec.h InfoObj.h DDInc.h VarJuego.h Mapa.h
		g++ -c -Wall -o PuenCae.o PuenCae.cpp

Puerta.o : Puerta.cpp RutinasSDL/rutinasSDL.h Puerta.h DDInc.h InfoObj.h VarJuego.h Mapa.h Colec.h Nicholas.h Cartel.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h
		g++ -c -Wall -o Puerta.o Puerta.cpp

Rayo.o : Rayo.cpp RutinasSDL/rutinasSDL.h Rayo.h Colec.h InfoObj.h DDInc.h VarJuego.h Mapa.h Explo.h
		g++ -c -Wall -o Rayo.o Rayo.cpp

Reboter.o : Reboter.cpp RutinasSDL/rutinasSDL.h Reboter.h DDInc.h InfoObj.h VarJuego.h Mapa.h Colec.h Nicholas.h Cartel.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h
		g++ -c -Wall -o Reboter.o Reboter.cpp

Robots.o : Robots.cpp RutinasSDL/rutinasSDL.h Robots.h InfoObj.h Colec.h Cartel.h DDInc.h VarJuego.h Mapa.h Nicholas.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h Tortuga.h
		g++ -c -Wall -o Robots.o Robots.cpp

Sauriolo.o : Sauriolo.cpp RutinasSDL/rutinasSDL.h Sauriolo.h InfoObj.h Colec.h Cartel.h DDInc.h VarJuego.h Mapa.h Nicholas.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h Tortuga.h
		g++ -c -Wall -o Sauriolo.o Sauriolo.cpp

Secuen.o : Secuen.cpp RutinasSDL/rutinasSDL.h Secuen.h InfoObj.h Colec.h VarJuego.h Mapa.h DDInc.h
		g++ -c -Wall -o Secuen.o Secuen.cpp

Teleport.o : Teleport.cpp RutinasSDL/rutinasSDL.h Teleport.h DDInc.h InfoObj.h VarJuego.h Mapa.h Colec.h Nicholas.h Cartel.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h
		g++ -c -Wall -o Teleport.o Teleport.cpp

Tortuga.o : Tortuga.cpp RutinasSDL/rutinasSDL.h Tortuga.h InfoObj.h VarJuego.h Mapa.h DDInc.h Colec.h Cartel.h Nicholas.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h
		g++ -c -Wall -o Tortuga.o Tortuga.cpp

Triturin.o : Triturin.cpp RutinasSDL/rutinasSDL.h Triturin.h Colec.h InfoObj.h DDInc.h VarJuego.h Mapa.h PuenCae.h
		g++ -c -Wall -o Triturin.o Triturin.cpp

VarJuego.o : VarJuego.cpp RutinasSDL/rutinasSDL.h VarJuego.h InfoObj.h Mapa.h DDInc.h
		g++ -c -Wall -o VarJuego.o VarJuego.cpp

VerdeLoc.o : VerdeLoc.cpp RutinasSDL/rutinasSDL.h VerdeLoc.h InfoObj.h Colec.h Cartel.h DDInc.h VarJuego.h Mapa.h Nicholas.h Moneda.h BolFuego.h Explo.h PuenCae.h Triturin.h Rayo.h Tortuga.h
		g++ -c -Wall -o VerdeLoc.o VerdeLoc.cpp

RutinasSDL/rutinasSDL.o : RutinasSDL/rutinasSDL.cpp RutinasSDL/rutinasSDL.h
		g++ -c -Wall -o RutinasSDL/rutinasSDL.o RutinasSDL/rutinasSDL.cpp

.PHONY : clean

clean :
	rm -f *.o
	rm -f RutinasSDL/rutinasSDL.o
