g++ -c -Wall -o Bichoto.o Bichoto.cpp
g++ -c -Wall -o BolFuego.o BolFuego.cpp
g++ -c -Wall -o BolFuSal.o BolFuSal.cpp
g++ -c -Wall -o CaeCucho.o CaeCucho.cpp
g++ -c -Wall -o Caparatuzo.o Caparatuzo.cpp
g++ -c -Wall -o Cartel.o Cartel.cpp
g++ -c -Wall -o Colec.o Colec.cpp
g++ -c -Wall -o Explo.o Explo.cpp
g++ -c -Wall -o Juanchi.o Juanchi.cpp
g++ -c -Wall -o Mapa.o Mapa.cpp
g++ -c -Wall -o Moneda.o Moneda.cpp
g++ -c -Wall -o Nichobros.o Nichobros.cpp
g++ -c -Wall -o Nicholas.o Nicholas.cpp
g++ -c -Wall -o PinPalo.o PinPalo.cpp
g++ -c -Wall -o PlatCae.o PlatCae.cpp
g++ -c -Wall -o PlatLat.o PlatLat.cpp
g++ -c -Wall -o PuenCae.o PuenCae.cpp
g++ -c -Wall -o Puerta.o Puerta.cpp
g++ -c -Wall -o Rayo.o Rayo.cpp
g++ -c -Wall -o Reboter.o Reboter.cpp
g++ -c -Wall -o Robots.o Robots.cpp
g++ -c -Wall -o Sauriolo.o Sauriolo.cpp
g++ -c -Wall -o Secuen.o Secuen.cpp
g++ -c -Wall -o Teleport.o Teleport.cpp
g++ -c -Wall -o Tortuga.o Tortuga.cpp
g++ -c -Wall -o Triturin.o Triturin.cpp
g++ -c -Wall -o VarJuego.o VarJuego.cpp
g++ -c -Wall -o VerdeLoc.o VerdeLoc.cpp
g++ -c -Wall -o RutinasSDL/rutinasSDL.o RutinasSDL/rutinasSDL.cpp
g++ Bichoto.o BolFuego.o BolFuSal.o CaeCucho.o Caparatuzo.o Cartel.o Colec.o Explo.o Juanchi.o Mapa.o Moneda.o Nichobros.o Nicholas.o PinPalo.o PlatCae.o PlatLat.o PuenCae.o Puerta.o Rayo.o Reboter.o Robots.o Sauriolo.o Secuen.o Teleport.o Tortuga.o Triturin.o VarJuego.o VerdeLoc.o RutinasSDL/rutinasSDL.o -o Nichobros -lmingw32 -lSDLmain -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
